package rentcarmanagerment.view;

import java.awt.Dimension;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import rentcarmanagerment.dao.LoginDAO;

/**
 *
 * @author Tran Phuc
 */
public class LoginFrm extends javax.swing.JFrame {

    public static String name = "";
    
    public LoginFrm() {
        Dimension size = new Dimension(400, 200);
        this.setSize(size);
        this.setMinimumSize(size);
        this.setTitle("Manager login");
        initComponents();
        lbLoginFail.setVisible(false);
        lbRoleFail.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grRole = new javax.swing.ButtonGroup();
        btnLogin = new javax.swing.JButton();
        btnCancle = new javax.swing.JButton();
        lbUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lbPassword = new javax.swing.JLabel();
        lbLoginFail = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        rAdmin = new javax.swing.JRadioButton();
        rMod = new javax.swing.JRadioButton();
        rEmp = new javax.swing.JRadioButton();
        lbRoleFail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnCancle.setText("Cancle");
        btnCancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancleActionPerformed(evt);
            }
        });

        lbUsername.setText("Username:");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        lbPassword.setText("Password:");

        lbLoginFail.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbLoginFail.setForeground(new java.awt.Color(255, 51, 51));
        lbLoginFail.setText("Wrong username or password, please try again!");

        grRole.add(rAdmin);
        rAdmin.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        rAdmin.setText("Admin");

        grRole.add(rMod);
        rMod.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        rMod.setText("Manager/Mod");

        grRole.add(rEmp);
        rEmp.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        rEmp.setText("Employee");

        lbRoleFail.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbRoleFail.setForeground(new java.awt.Color(255, 51, 51));
        lbRoleFail.setText("Please choose your role!");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\ptit-cnpm\\quanlithuexetulai\\image\\car.png")); // NOI18N
        jLabel1.setText("Rent Car Management");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbPassword)
                                    .addComponent(lbUsername))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rMod)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btnLogin)
                                .addGap(35, 35, 35)
                                .addComponent(btnCancle))
                            .addComponent(jLabel1))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbRoleFail)
                            .addComponent(lbLoginFail))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbPassword)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rMod, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLoginFail)
                    .addComponent(rEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbRoleFail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnCancle)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String role = null;
        if (rAdmin.isSelected()) {
            role = "ADM";
        } else if (rMod.isSelected()) {
            role = "MOD";
        } else if (rEmp.isSelected()) {
            role = "EMP";
        }

        LoginDAO dao = null;
        try {
            dao = new LoginDAO();
            System.out.println("Connected to database!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Cannot connect to database!");
        }
        if (dao != null) {
            try {
                name = dao.login(txtUsername.getText(), txtPassword.getText(), role);
                this.setVisible(false);
                new ManagerHomeFrm(name).setVisible(true);

            } catch (SQLException ex) {
                System.err.println("Login Failed! Wrong username or password!");
                lbLoginFail.setVisible(true);
            } catch (NullPointerException e) {
                System.out.println("Login Failed! Please choose your role!");
                lbRoleFail.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancleActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Sure you want to exit?",
                "Confirm to exit", JOptionPane.OK_CANCEL_OPTION);
        if (result == 0) {
            System.exit(0);
        }

    }//GEN-LAST:event_btnCancleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancle;
    private javax.swing.JButton btnLogin;
    private javax.swing.ButtonGroup grRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbLoginFail;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbRoleFail;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JRadioButton rAdmin;
    private javax.swing.JRadioButton rEmp;
    private javax.swing.JRadioButton rMod;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
