package rentcarmanagerment.view;

/**
 *
 * @author Tran Phuc
 */
public class StatisticHomeFrm extends javax.swing.JFrame {

    /**
     * Creates new form ViewReportFrm
     */
    public StatisticHomeFrm() {
        this.setTitle("Choose Report Type");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnByCar = new javax.swing.JButton();
        btnByTime = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mHome = new javax.swing.JMenu();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnByCar.setText("View By Car");
        btnByCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnByCarActionPerformed(evt);
            }
        });

        btnByTime.setText("View By Time");
        btnByTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnByTimeActionPerformed(evt);
            }
        });

        mHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\icons8-top-menu-24.png")); // NOI18N
        mHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mHomeMouseClicked(evt);
            }
        });
        jMenuBar1.add(mHome);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnByCar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(btnByTime)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnByCar)
                    .addComponent(btnByTime))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnByTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnByTimeActionPerformed
        this.setVisible(false);
        new StatByTimeFrm().setVisible(true);
    }//GEN-LAST:event_btnByTimeActionPerformed

    private void mHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mHomeMouseClicked
        this.setVisible(false);
        new ManagerHomeFrm().setVisible(true);
    }//GEN-LAST:event_mHomeMouseClicked

    private void btnByCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnByCarActionPerformed
        this.setVisible(false);
        new StatByCarFrm().setVisible(true);
    }//GEN-LAST:event_btnByCarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatisticHomeFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnByCar;
    private javax.swing.JButton btnByTime;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mHome;
    // End of variables declaration//GEN-END:variables
}
