package rentcarmanagerment.view;

import javax.swing.JFrame;

/**
 *
 * @author Tran Phuc
 */
public class StatByCarFrm extends JFrame {

    public StatByCarFrm() {
        super("Income statistic by car");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mHome = new javax.swing.JMenu();
        mType = new javax.swing.JMenu();
        itemByTime = new javax.swing.JMenuItem();
        itemByCar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Statistic by car");

        mHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\ptit-cnpm\\quanlithuexetulai\\image\\home-icon.png")); // NOI18N
        mHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mHomeMouseClicked(evt);
            }
        });
        jMenuBar1.add(mHome);

        mType.setText("Type");
        mType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mTypeMouseEntered(evt);
            }
        });

        itemByTime.setText("By Time");
        itemByTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemByTimeActionPerformed(evt);
            }
        });
        mType.add(itemByTime);

        itemByCar.setText("By Car");
        itemByCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemByCarActionPerformed(evt);
            }
        });
        mType.add(itemByCar);

        jMenuBar1.add(mType);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mHomeMouseClicked
        this.setVisible(false);
        new ManagerHomeFrm(LoginFrm.name).setVisible(true);
    }//GEN-LAST:event_mHomeMouseClicked

    private void itemByTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemByTimeActionPerformed
        this.setVisible(false);
        new StatByMonthFrm().setVisible(true);
    }//GEN-LAST:event_itemByTimeActionPerformed

    private void itemByCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemByCarActionPerformed
        System.out.println("Already Showed");
    }//GEN-LAST:event_itemByCarActionPerformed

    private void mTypeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mTypeMouseEntered
        mType.doClick();
    }//GEN-LAST:event_mTypeMouseEntered

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemByCar;
    private javax.swing.JMenuItem itemByTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mHome;
    private javax.swing.JMenu mType;
    // End of variables declaration//GEN-END:variables
}
